# Welcome to Jekyll!
#

# Site settings
title: BioHackaton 2018
description: |
  **Paris - November - 2018**
owner: Elixir HUB # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: arcila@ebi.ac.uk
baseurl: "/biohackaton/2018" # the subpath of your site, e.g. /blog
url: "https://elixir-europe.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/elixireurope
  github: https://github.com/elixir-europe
  linkedin-square: https://www.linkedin.com/company/9501702/e
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
